deps_config := \
	src/lib/Kconfig \
	src/drivers/intel/fsp2_0/Kconfig.debug_blob \
	src/vendorcode/amd/opensil/Kconfig.debug \
	src/cpu/x86/Kconfig.debug_cpu \
	payloads/external/Memtest86Plus/Kconfig.secondary \
	payloads/external/coreDOOM/Kconfig.secondary \
	payloads/external/edk2/Kconfig.dasharo \
	payloads/external/BOOTBOOT/Kconfig \
	payloads/external/FILO/Kconfig \
	payloads/external/GRUB2/Kconfig \
	payloads/external/LinuxBoot/Kconfig \
	payloads/external/SeaBIOS/Kconfig \
	payloads/external/U-Boot/Kconfig \
	payloads/external/depthcharge/Kconfig \
	payloads/external/edk2/Kconfig \
	payloads/external/iPXE/Kconfig \
	payloads/external/leanefi/Kconfig \
	payloads/external/linux/Kconfig \
	payloads/external/skiboot/Kconfig \
	payloads/external/BOOTBOOT/Kconfig.name \
	payloads/external/FILO/Kconfig.name \
	payloads/external/GRUB2/Kconfig.name \
	payloads/external/LinuxBoot/Kconfig.name \
	payloads/external/SeaBIOS/Kconfig.name \
	payloads/external/U-Boot/Kconfig.name \
	payloads/external/depthcharge/Kconfig.name \
	payloads/external/edk2/Kconfig.name \
	payloads/external/leanefi/Kconfig.name \
	payloads/external/linux/Kconfig.name \
	payloads/external/skiboot/Kconfig.name \
	payloads/Kconfig \
	src/console/Kconfig \
	src/acpi/Kconfig \
	src/vendorcode/eltan/security/verified_boot/Kconfig \
	src/vendorcode/eltan/security/mboot/Kconfig \
	src/vendorcode/eltan/security/Kconfig \
	src/security/lockdown/Kconfig \
	src/security/intel/cbnt/Kconfig \
	src/security/intel/stm/Kconfig \
	src/security/intel/txt/Kconfig \
	src/security/intel/Kconfig \
	src/security/memory/Kconfig \
	src/security/tpm/tss/vendor/cr50/Kconfig \
	src/security/tpm/Kconfig \
	src/security/vboot/Kconfig \
	src/lib/Kconfig.cbfs_verification \
	src/security/Kconfig \
	src/commonlib/storage/Kconfig \
	src/drivers/gfx/nvidia/optimus/Kconfig \
	src/drivers/intel/fsp2_0/ppi/Kconfig \
	src/drivers/intel/usb4/retimer/Kconfig \
	src/drivers/net/phy/m88e1512/Kconfig \
	src/drivers/pcie/rtd3/device/Kconfig \
	src/drivers/acpi/thermal_zone/Kconfig \
	src/drivers/amd/agesa/Kconfig \
	src/drivers/amd/i2s_machine_dev/Kconfig \
	src/drivers/analogix/anx7625/Kconfig \
	src/drivers/aspeed/ast2050/Kconfig \
	src/drivers/aspeed/common/Kconfig \
	src/drivers/emulation/qemu/Kconfig \
	src/drivers/generic/adau7002/Kconfig \
	src/drivers/generic/alc1015/Kconfig \
	src/drivers/generic/bayhub/Kconfig \
	src/drivers/generic/bayhub_lv2/Kconfig \
	src/drivers/generic/cbfs-serial/Kconfig \
	src/drivers/generic/cbfs-uuid/Kconfig \
	src/drivers/generic/gpio_keys/Kconfig \
	src/drivers/generic/max98357a/Kconfig \
	src/drivers/generic/nau8315/Kconfig \
	src/drivers/genesyslogic/gl9750/Kconfig \
	src/drivers/genesyslogic/gl9755/Kconfig \
	src/drivers/genesyslogic/gl9763e/Kconfig \
	src/drivers/gfx/generic/Kconfig \
	src/drivers/i2c/at24rf08c/Kconfig \
	src/drivers/i2c/ck505/Kconfig \
	src/drivers/i2c/cs35l53/Kconfig \
	src/drivers/i2c/cs42l42/Kconfig \
	src/drivers/i2c/da7219/Kconfig \
	src/drivers/i2c/designware/Kconfig \
	src/drivers/i2c/generic/Kconfig \
	src/drivers/i2c/gpiomux/Kconfig \
	src/drivers/i2c/hid/Kconfig \
	src/drivers/i2c/lm96000/Kconfig \
	src/drivers/i2c/max98373/Kconfig \
	src/drivers/i2c/max98390/Kconfig \
	src/drivers/i2c/max98396/Kconfig \
	src/drivers/i2c/max98927/Kconfig \
	src/drivers/i2c/nau8825/Kconfig \
	src/drivers/i2c/nct7802y/Kconfig \
	src/drivers/i2c/pca9538/Kconfig \
	src/drivers/i2c/pcf8523/Kconfig \
	src/drivers/i2c/pi608gp/Kconfig \
	src/drivers/i2c/ptn3460/Kconfig \
	src/drivers/i2c/rt1011/Kconfig \
	src/drivers/i2c/rt5645/Kconfig \
	src/drivers/i2c/rt5663/Kconfig \
	src/drivers/i2c/rtd2132/Kconfig \
	src/drivers/i2c/rv3028c7/Kconfig \
	src/drivers/i2c/rx6110sa/Kconfig \
	src/drivers/i2c/sx9310/Kconfig \
	src/drivers/i2c/sx9324/Kconfig \
	src/drivers/i2c/sx9360/Kconfig \
	src/drivers/i2c/tas5825m/Kconfig \
	src/drivers/i2c/tpm/Kconfig \
	src/drivers/i2c/ww_ring/Kconfig \
	src/drivers/intel/dptf/Kconfig \
	src/drivers/intel/fsp1_1/Kconfig \
	src/drivers/intel/fsp2_0/Kconfig \
	src/drivers/intel/gma/Kconfig \
	src/drivers/intel/i210/Kconfig \
	src/drivers/intel/ish/Kconfig \
	src/drivers/intel/mipi_camera/Kconfig \
	src/drivers/intel/pmc_mux/Kconfig \
	src/drivers/intel/ptt/Kconfig \
	src/drivers/intel/soundwire/Kconfig \
	src/drivers/ipmi/ocp/Kconfig \
	src/drivers/lenovo/hybrid_graphics/Kconfig \
	src/drivers/maxim/max77686/Kconfig \
	src/drivers/nxp/uwb/Kconfig \
	src/drivers/ocp/dmi/Kconfig \
	src/drivers/ocp/ewl/Kconfig \
	src/drivers/ocp/vpd/Kconfig \
	src/drivers/parade/ps8625/Kconfig \
	src/drivers/parade/ps8640/Kconfig \
	src/drivers/pc80/pc/Kconfig \
	src/drivers/pc80/rtc/Kconfig \
	src/drivers/pc80/tpm/Kconfig \
	src/drivers/pc80/vga/Kconfig \
	src/drivers/pcie/generic/Kconfig \
	src/drivers/ricoh/rce822/Kconfig \
	src/drivers/secunet/dmi/Kconfig \
	src/drivers/siemens/nc_fpga/Kconfig \
	src/drivers/sil/3114/Kconfig \
	src/drivers/soundwire/alc1308/Kconfig \
	src/drivers/soundwire/alc5682/Kconfig \
	src/drivers/soundwire/alc711/Kconfig \
	src/drivers/soundwire/cs42l42/Kconfig \
	src/drivers/soundwire/max98363/Kconfig \
	src/drivers/soundwire/max98373/Kconfig \
	src/drivers/spi/acpi/Kconfig \
	src/drivers/spi/tpm/Kconfig \
	src/drivers/ti/sn65dsi86bridge/Kconfig \
	src/drivers/ti/tps65090/Kconfig \
	src/drivers/ti/tps65913/Kconfig \
	src/drivers/uart/acpi/Kconfig \
	src/drivers/usb/acpi/Kconfig \
	src/drivers/usb/hub/Kconfig \
	src/drivers/usb/pci_xhci/Kconfig \
	src/drivers/wifi/generic/Kconfig \
	src/drivers/wwan/fm/Kconfig \
	src/drivers/ams/Kconfig \
	src/drivers/asmedia/Kconfig \
	src/drivers/camera/Kconfig \
	src/drivers/crb/Kconfig \
	src/drivers/efi/Kconfig \
	src/drivers/elog/Kconfig \
	src/drivers/ipmi/Kconfig \
	src/drivers/lenovo/Kconfig \
	src/drivers/mipi/Kconfig \
	src/drivers/mrc_cache/Kconfig \
	src/drivers/net/Kconfig \
	src/drivers/option/Kconfig \
	src/drivers/smmstore/Kconfig \
	src/drivers/sof/Kconfig \
	src/drivers/spi/Kconfig \
	src/drivers/tpm/Kconfig \
	src/drivers/uart/Kconfig \
	src/drivers/usb/Kconfig \
	src/drivers/vpd/Kconfig \
	src/device/dram/Kconfig \
	src/device/Kconfig \
	src/arch/arm64/armv8/Kconfig \
	src/arch/arm/armv7/Kconfig \
	src/arch/arm/armv4/Kconfig \
	src/arch/arm/Kconfig \
	src/arch/arm64/Kconfig \
	src/arch/ppc64/Kconfig \
	src/arch/riscv/Kconfig \
	src/arch/x86/Kconfig \
	src/vendorcode/google/chromeos/Kconfig \
	src/vendorcode/amd/opensil/Kconfig \
	src/vendorcode/amd/pi/Kconfig \
	src/vendorcode/amd/Kconfig \
	src/vendorcode/cavium/Kconfig \
	src/vendorcode/dasharo/Kconfig \
	src/vendorcode/google/Kconfig \
	src/vendorcode/intel/Kconfig \
	src/vendorcode/siemens/Kconfig \
	src/southbridge/intel/common/firmware/Kconfig \
	src/ec/google/chromeec/audio_codec/Kconfig \
	src/ec/google/chromeec/i2c_tunnel/Kconfig \
	src/ec/google/chromeec/mux/Kconfig \
	src/ec/51nb/npce985la0dx/Kconfig \
	src/ec/clevo/it5570e/Kconfig \
	src/ec/compal/ene932/Kconfig \
	src/ec/dasharo/ec/Kconfig \
	src/ec/dell/mec5035/Kconfig \
	src/ec/google/chromeec/Kconfig \
	src/ec/google/common/Kconfig \
	src/ec/google/wilco/Kconfig \
	src/ec/hp/kbc1126/Kconfig \
	src/ec/kontron/it8516e/Kconfig \
	src/ec/kontron/kempld/Kconfig \
	src/ec/lenovo/h8/Kconfig \
	src/ec/lenovo/pmh7/Kconfig \
	src/ec/purism/librem-ec/Kconfig \
	src/ec/quanta/ene_kb3940q/Kconfig \
	src/ec/quanta/it8518/Kconfig \
	src/ec/roda/it8518/Kconfig \
	src/ec/smsc/mec1308/Kconfig \
	src/ec/starlabs/merlin/Kconfig \
	src/ec/system76/ec/Kconfig \
	src/ec/acpi/Kconfig \
	src/superio/aspeed/ast2400/Kconfig \
	src/superio/aspeed/common/Kconfig \
	src/superio/fintek/common/Kconfig \
	src/superio/fintek/f71808a/Kconfig \
	src/superio/fintek/f71859/Kconfig \
	src/superio/fintek/f71863fg/Kconfig \
	src/superio/fintek/f71869ad/Kconfig \
	src/superio/fintek/f81803a/Kconfig \
	src/superio/fintek/f81865f/Kconfig \
	src/superio/fintek/f81866d/Kconfig \
	src/superio/ite/common/Kconfig \
	src/superio/ite/it8528e/Kconfig \
	src/superio/ite/it8613e/Kconfig \
	src/superio/ite/it8623e/Kconfig \
	src/superio/ite/it8625e/Kconfig \
	src/superio/ite/it8629e/Kconfig \
	src/superio/ite/it8659e/Kconfig \
	src/superio/ite/it8712f/Kconfig \
	src/superio/ite/it8718f/Kconfig \
	src/superio/ite/it8720f/Kconfig \
	src/superio/ite/it8721f/Kconfig \
	src/superio/ite/it8728f/Kconfig \
	src/superio/ite/it8772f/Kconfig \
	src/superio/ite/it8783ef/Kconfig \
	src/superio/ite/it8784e/Kconfig \
	src/superio/ite/it8786e/Kconfig \
	src/superio/nsc/common/Kconfig \
	src/superio/nsc/pc87382/Kconfig \
	src/superio/nsc/pc87384/Kconfig \
	src/superio/nsc/pc87392/Kconfig \
	src/superio/nsc/pc87417/Kconfig \
	src/superio/nuvoton/common/Kconfig \
	src/superio/nuvoton/nct5104d/Kconfig \
	src/superio/nuvoton/nct5539d/Kconfig \
	src/superio/nuvoton/nct5572d/Kconfig \
	src/superio/nuvoton/nct6687d/Kconfig \
	src/superio/nuvoton/nct6776/Kconfig \
	src/superio/nuvoton/nct6779d/Kconfig \
	src/superio/nuvoton/nct6791d/Kconfig \
	src/superio/nuvoton/npcd378/Kconfig \
	src/superio/nuvoton/wpcm450/Kconfig \
	src/superio/renesas/m3885x/Kconfig \
	src/superio/smsc/fdc37n972/Kconfig \
	src/superio/smsc/kbc1100/Kconfig \
	src/superio/smsc/lpc47m10x/Kconfig \
	src/superio/smsc/lpc47m15x/Kconfig \
	src/superio/smsc/lpc47n207/Kconfig \
	src/superio/smsc/lpc47n217/Kconfig \
	src/superio/smsc/lpc47n227/Kconfig \
	src/superio/smsc/mec1308/Kconfig \
	src/superio/smsc/sch5545/Kconfig \
	src/superio/smsc/sch555x/Kconfig \
	src/superio/smsc/sio1007/Kconfig \
	src/superio/smsc/sio1036/Kconfig \
	src/superio/smsc/sio10n268/Kconfig \
	src/superio/smsc/smscsuperio/Kconfig \
	src/superio/winbond/common/Kconfig \
	src/superio/winbond/w83627dhg/Kconfig \
	src/superio/winbond/w83627ehg/Kconfig \
	src/superio/winbond/w83627hf/Kconfig \
	src/superio/winbond/w83627thg/Kconfig \
	src/superio/winbond/w83627uhg/Kconfig \
	src/superio/winbond/w83667hg-a/Kconfig \
	src/superio/winbond/w83977tf/Kconfig \
	src/superio/winbond/wpcd376i/Kconfig \
	src/southbridge/intel/common/Kconfig.common \
	src/southbridge/amd/pi/hudson/Kconfig \
	src/southbridge/amd/pi/Kconfig \
	src/southbridge/intel/bd82x6x/Kconfig \
	src/southbridge/intel/i82371eb/Kconfig \
	src/southbridge/intel/i82801dx/Kconfig \
	src/southbridge/intel/i82801gx/Kconfig \
	src/southbridge/intel/i82801ix/Kconfig \
	src/southbridge/intel/i82801jx/Kconfig \
	src/southbridge/intel/i82870/Kconfig \
	src/southbridge/intel/ibexpeak/Kconfig \
	src/southbridge/intel/lynxpoint/Kconfig \
	src/southbridge/ricoh/rl5c476/Kconfig \
	src/southbridge/ti/pci1x2x/Kconfig \
	src/southbridge/ti/pci7420/Kconfig \
	src/southbridge/ti/pcixx12/Kconfig \
	src/northbridge/intel/common/Kconfig.common \
	src/northbridge/amd/pi/00730F01/Kconfig \
	src/northbridge/amd/pi/Kconfig \
	src/northbridge/intel/e7505/Kconfig \
	src/northbridge/intel/gm45/Kconfig \
	src/northbridge/intel/haswell/Kconfig \
	src/northbridge/intel/i440bx/Kconfig \
	src/northbridge/intel/i945/Kconfig \
	src/northbridge/intel/ironlake/Kconfig \
	src/northbridge/intel/pineview/Kconfig \
	src/northbridge/intel/sandybridge/Kconfig \
	src/northbridge/intel/x4x/Kconfig \
	src/northbridge/via/cx700/Kconfig \
	src/cpu/via/c7/Kconfig \
	src/cpu/intel/car/non-evict/Kconfig \
	src/cpu/intel/microcode/Kconfig \
	src/cpu/intel/common/Kconfig \
	src/cpu/intel/turbo/Kconfig \
	src/cpu/intel/fit/Kconfig \
	src/cpu/intel/socket_OTHER/Kconfig \
	src/cpu/intel/socket_LGA4677/Kconfig \
	src/cpu/intel/socket_LGA4189/Kconfig \
	src/cpu/intel/socket_LGA3647_1/Kconfig \
	src/cpu/intel/socket_LGA1700/Kconfig \
	src/cpu/intel/socket_LGA775/Kconfig \
	src/cpu/intel/socket_441/Kconfig \
	src/cpu/intel/socket_mPGA604/Kconfig \
	src/cpu/intel/socket_p/Kconfig \
	src/cpu/intel/socket_m/Kconfig \
	src/cpu/intel/socket_FCBGA559/Kconfig \
	src/cpu/intel/socket_BGA956/Kconfig \
	src/cpu/intel/slot_1/Kconfig \
	src/cpu/intel/haswell/Kconfig \
	src/cpu/intel/model_f4x/Kconfig \
	src/cpu/intel/model_f3x/Kconfig \
	src/cpu/intel/model_f2x/Kconfig \
	src/cpu/intel/model_2065x/Kconfig \
	src/cpu/intel/model_206ax/Kconfig \
	src/cpu/intel/model_106cx/Kconfig \
	src/cpu/intel/model_1067x/Kconfig \
	src/cpu/intel/model_6fx/Kconfig \
	src/cpu/intel/model_6ex/Kconfig \
	src/cpu/intel/model_6bx/Kconfig \
	src/cpu/intel/model_68x/Kconfig \
	src/cpu/intel/model_67x/Kconfig \
	src/cpu/intel/model_65x/Kconfig \
	src/cpu/intel/model_6xx/Kconfig \
	src/cpu/armltd/cortex-a9/Kconfig \
	src/cpu/amd/pi/00730F01/Kconfig \
	src/cpu/amd/pi/Kconfig \
	src/cpu/amd/Kconfig \
	src/cpu/armltd/Kconfig \
	src/cpu/intel/Kconfig \
	src/cpu/power9/Kconfig \
	src/cpu/qemu-power8/Kconfig \
	src/cpu/qemu-x86/Kconfig \
	src/cpu/via/Kconfig \
	src/cpu/x86/Kconfig \
	src/cpu/Kconfig \
	src/soc/intel/common/basecode/debug/Kconfig \
	src/soc/intel/common/basecode/ramtop/Kconfig \
	src/soc/intel/common/basecode/Kconfig \
	src/soc/intel/common/pch/lockdown/Kconfig \
	src/soc/intel/common/pch/Kconfig \
	src/soc/intel/common/block/pcie/rtd3/Kconfig \
	src/soc/intel/common/block/acpi/Kconfig \
	src/soc/intel/common/block/chip/Kconfig \
	src/soc/intel/common/block/cnvi/Kconfig \
	src/soc/intel/common/block/cpu/Kconfig \
	src/soc/intel/common/block/cse/Kconfig \
	src/soc/intel/common/block/dsp/Kconfig \
	src/soc/intel/common/block/dtt/Kconfig \
	src/soc/intel/common/block/fast_spi/Kconfig \
	src/soc/intel/common/block/gpio/Kconfig \
	src/soc/intel/common/block/gpmr/Kconfig \
	src/soc/intel/common/block/graphics/Kconfig \
	src/soc/intel/common/block/gspi/Kconfig \
	src/soc/intel/common/block/hda/Kconfig \
	src/soc/intel/common/block/i2c/Kconfig \
	src/soc/intel/common/block/imc/Kconfig \
	src/soc/intel/common/block/ioc/Kconfig \
	src/soc/intel/common/block/ipu/Kconfig \
	src/soc/intel/common/block/irq/Kconfig \
	src/soc/intel/common/block/itss/Kconfig \
	src/soc/intel/common/block/lpc/Kconfig \
	src/soc/intel/common/block/lpss/Kconfig \
	src/soc/intel/common/block/memory/Kconfig \
	src/soc/intel/common/block/oc_wdt/Kconfig \
	src/soc/intel/common/block/p2sb/Kconfig \
	src/soc/intel/common/block/pcie/Kconfig \
	src/soc/intel/common/block/pcr/Kconfig \
	src/soc/intel/common/block/pmc/Kconfig \
	src/soc/intel/common/block/power_limit/Kconfig \
	src/soc/intel/common/block/rtc/Kconfig \
	src/soc/intel/common/block/sata/Kconfig \
	src/soc/intel/common/block/scs/Kconfig \
	src/soc/intel/common/block/sgx/Kconfig \
	src/soc/intel/common/block/smbus/Kconfig \
	src/soc/intel/common/block/smm/Kconfig \
	src/soc/intel/common/block/spi/Kconfig \
	src/soc/intel/common/block/sram/Kconfig \
	src/soc/intel/common/block/systemagent-server/Kconfig \
	src/soc/intel/common/block/systemagent/Kconfig \
	src/soc/intel/common/block/tcss/Kconfig \
	src/soc/intel/common/block/thermal/Kconfig \
	src/soc/intel/common/block/timer/Kconfig \
	src/soc/intel/common/block/tracehub/Kconfig \
	src/soc/intel/common/block/uart/Kconfig \
	src/soc/intel/common/block/usb4/Kconfig \
	src/soc/intel/common/block/vtd/Kconfig \
	src/soc/intel/common/block/xdci/Kconfig \
	src/soc/intel/common/block/xhci/Kconfig \
	src/soc/intel/common/block/Kconfig \
	src/soc/amd/common/psp_verstage/Kconfig \
	src/soc/amd/common/pi/Kconfig \
	src/soc/amd/common/fsp/pci/Kconfig \
	src/soc/amd/common/fsp/Kconfig \
	src/soc/amd/common/block/acp/Kconfig \
	src/soc/amd/common/block/acpi/Kconfig \
	src/soc/amd/common/block/acpimmio/Kconfig \
	src/soc/amd/common/block/alink/Kconfig \
	src/soc/amd/common/block/aoac/Kconfig \
	src/soc/amd/common/block/apob/Kconfig \
	src/soc/amd/common/block/cpu/Kconfig \
	src/soc/amd/common/block/data_fabric/Kconfig \
	src/soc/amd/common/block/emmc/Kconfig \
	src/soc/amd/common/block/gpio/Kconfig \
	src/soc/amd/common/block/gpp_clk/Kconfig \
	src/soc/amd/common/block/graphics/Kconfig \
	src/soc/amd/common/block/hda/Kconfig \
	src/soc/amd/common/block/i2c/Kconfig \
	src/soc/amd/common/block/iommu/Kconfig \
	src/soc/amd/common/block/lpc/Kconfig \
	src/soc/amd/common/block/pci/Kconfig \
	src/soc/amd/common/block/pm/Kconfig \
	src/soc/amd/common/block/psp/Kconfig \
	src/soc/amd/common/block/root_complex/Kconfig \
	src/soc/amd/common/block/sata/Kconfig \
	src/soc/amd/common/block/simnow/Kconfig \
	src/soc/amd/common/block/smbus/Kconfig \
	src/soc/amd/common/block/smi/Kconfig \
	src/soc/amd/common/block/smn/Kconfig \
	src/soc/amd/common/block/smu/Kconfig \
	src/soc/amd/common/block/spi/Kconfig \
	src/soc/amd/common/block/stb/Kconfig \
	src/soc/amd/common/block/uart/Kconfig \
	src/soc/amd/common/block/xhci/Kconfig \
	src/soc/amd/common/Kconfig.common \
	src/soc/intel/common/Kconfig.common \
	src/soc/intel/xeon_sp/cpx/Kconfig \
	src/soc/intel/xeon_sp/gnr/Kconfig \
	src/soc/intel/xeon_sp/ras/Kconfig \
	src/soc/intel/xeon_sp/skx/Kconfig \
	src/soc/intel/xeon_sp/spr/Kconfig \
	src/soc/intel/broadwell/pch/Kconfig \
	src/soc/amd/cezanne/Kconfig \
	src/soc/amd/genoa_poc/Kconfig \
	src/soc/amd/glinda/Kconfig \
	src/soc/amd/mendocino/Kconfig \
	src/soc/amd/phoenix/Kconfig \
	src/soc/amd/picasso/Kconfig \
	src/soc/amd/stoneyridge/Kconfig \
	src/soc/cavium/cn81xx/Kconfig \
	src/soc/cavium/common/Kconfig \
	src/soc/example/min86/Kconfig \
	src/soc/ibm/power9/Kconfig \
	src/soc/intel/alderlake/Kconfig \
	src/soc/intel/apollolake/Kconfig \
	src/soc/intel/baytrail/Kconfig \
	src/soc/intel/braswell/Kconfig \
	src/soc/intel/broadwell/Kconfig \
	src/soc/intel/cannonlake/Kconfig \
	src/soc/intel/denverton_ns/Kconfig \
	src/soc/intel/elkhartlake/Kconfig \
	src/soc/intel/jasperlake/Kconfig \
	src/soc/intel/meteorlake/Kconfig \
	src/soc/intel/pantherlake/Kconfig \
	src/soc/intel/skylake/Kconfig \
	src/soc/intel/snowridge/Kconfig \
	src/soc/intel/tigerlake/Kconfig \
	src/soc/intel/xeon_sp/Kconfig \
	src/soc/mediatek/common/Kconfig \
	src/soc/mediatek/mt8173/Kconfig \
	src/soc/mediatek/mt8183/Kconfig \
	src/soc/mediatek/mt8186/Kconfig \
	src/soc/mediatek/mt8188/Kconfig \
	src/soc/mediatek/mt8189/Kconfig \
	src/soc/mediatek/mt8192/Kconfig \
	src/soc/mediatek/mt8195/Kconfig \
	src/soc/mediatek/mt8196/Kconfig \
	src/soc/nvidia/tegra124/Kconfig \
	src/soc/nvidia/tegra210/Kconfig \
	src/soc/qualcomm/common/Kconfig \
	src/soc/qualcomm/ipq40xx/Kconfig \
	src/soc/qualcomm/ipq806x/Kconfig \
	src/soc/qualcomm/qcs405/Kconfig \
	src/soc/qualcomm/sc7180/Kconfig \
	src/soc/qualcomm/sc7280/Kconfig \
	src/soc/rockchip/rk3288/Kconfig \
	src/soc/rockchip/rk3399/Kconfig \
	src/soc/samsung/exynos5250/Kconfig \
	src/soc/samsung/exynos5420/Kconfig \
	src/soc/sifive/fu540/Kconfig \
	src/soc/sifive/fu740/Kconfig \
	src/soc/ti/am335x/Kconfig \
	src/soc/ucb/riscv/Kconfig \
	src/mainboard/via/epia-ex/Kconfig \
	src/mainboard/via/epia-ex/Kconfig.name \
	src/mainboard/up/squared/Kconfig \
	src/mainboard/up/squared/Kconfig.name \
	src/mainboard/topton/adl/Kconfig \
	src/mainboard/topton/adl/Kconfig.name \
	src/mainboard/ti/beaglebone/Kconfig \
	src/mainboard/ti/beaglebone/Kconfig.name \
	src/mainboard/system76/addw1/Kconfig \
	src/mainboard/system76/adl/Kconfig \
	src/mainboard/system76/bonw14/Kconfig \
	src/mainboard/system76/cml-u/Kconfig \
	src/mainboard/system76/gaze15/Kconfig \
	src/mainboard/system76/kbl-u/Kconfig \
	src/mainboard/system76/mtl/Kconfig \
	src/mainboard/system76/oryp5/Kconfig \
	src/mainboard/system76/oryp6/Kconfig \
	src/mainboard/system76/rpl/Kconfig \
	src/mainboard/system76/tgl-h/Kconfig \
	src/mainboard/system76/tgl-u/Kconfig \
	src/mainboard/system76/whl-u/Kconfig \
	src/mainboard/system76/addw1/Kconfig.name \
	src/mainboard/system76/adl/Kconfig.name \
	src/mainboard/system76/bonw14/Kconfig.name \
	src/mainboard/system76/cml-u/Kconfig.name \
	src/mainboard/system76/gaze15/Kconfig.name \
	src/mainboard/system76/kbl-u/Kconfig.name \
	src/mainboard/system76/mtl/Kconfig.name \
	src/mainboard/system76/oryp5/Kconfig.name \
	src/mainboard/system76/oryp6/Kconfig.name \
	src/mainboard/system76/rpl/Kconfig.name \
	src/mainboard/system76/tgl-h/Kconfig.name \
	src/mainboard/system76/tgl-u/Kconfig.name \
	src/mainboard/system76/whl-u/Kconfig.name \
	src/mainboard/supermicro/x10slm-f/Kconfig \
	src/mainboard/supermicro/x11-lga1151-series/Kconfig \
	src/mainboard/supermicro/x9sae/Kconfig \
	src/mainboard/supermicro/x9scl/Kconfig \
	src/mainboard/supermicro/x10slm-f/Kconfig.name \
	src/mainboard/supermicro/x11-lga1151-series/Kconfig.name \
	src/mainboard/supermicro/x9sae/Kconfig.name \
	src/mainboard/supermicro/x9scl/Kconfig.name \
	src/mainboard/starlabs/byte_adl/Kconfig \
	src/mainboard/starlabs/lite/Kconfig \
	src/mainboard/starlabs/starbook/Kconfig \
	src/mainboard/starlabs/starfighter/Kconfig \
	src/mainboard/starlabs/starlite_adl/Kconfig \
	src/mainboard/starlabs/byte_adl/Kconfig.name \
	src/mainboard/starlabs/lite/Kconfig.name \
	src/mainboard/starlabs/starbook/Kconfig.name \
	src/mainboard/starlabs/starfighter/Kconfig.name \
	src/mainboard/starlabs/starlite_adl/Kconfig.name \
	src/mainboard/sifive/hifive-unleashed/Kconfig \
	src/mainboard/sifive/hifive-unmatched/Kconfig \
	src/mainboard/sifive/hifive-unleashed/Kconfig.name \
	src/mainboard/sifive/hifive-unmatched/Kconfig.name \
	src/mainboard/siemens/mc_ehl/variants/mc_ehl1/Kconfig \
	src/mainboard/siemens/mc_ehl/variants/mc_ehl2/Kconfig \
	src/mainboard/siemens/mc_ehl/variants/mc_ehl3/Kconfig \
	src/mainboard/siemens/mc_ehl/variants/mc_ehl4/Kconfig \
	src/mainboard/siemens/mc_ehl/variants/mc_ehl5/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl1/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl2/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl3/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl4/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl5/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl6/Kconfig \
	src/mainboard/siemens/mc_apl1/variants/mc_apl7/Kconfig \
	src/mainboard/siemens/fa_ehl/variants/fa_ehl/Kconfig \
	src/mainboard/siemens/chili/Kconfig \
	src/mainboard/siemens/fa_ehl/Kconfig \
	src/mainboard/siemens/mc_apl1/Kconfig \
	src/mainboard/siemens/mc_ehl/Kconfig \
	src/mainboard/siemens/chili/Kconfig.name \
	src/mainboard/siemens/fa_ehl/Kconfig.name \
	src/mainboard/siemens/mc_apl1/Kconfig.name \
	src/mainboard/siemens/mc_ehl/Kconfig.name \
	src/mainboard/sapphire/pureplatinumh61/Kconfig \
	src/mainboard/sapphire/pureplatinumh61/Kconfig.name \
	src/mainboard/samsung/lumpy/Kconfig \
	src/mainboard/samsung/stumpy/Kconfig \
	src/mainboard/samsung/lumpy/Kconfig.name \
	src/mainboard/samsung/stumpy/Kconfig.name \
	src/mainboard/roda/rk886ex/Kconfig \
	src/mainboard/roda/rk9/Kconfig \
	src/mainboard/roda/rv11/Kconfig \
	src/mainboard/roda/rk886ex/Kconfig.name \
	src/mainboard/roda/rk9/Kconfig.name \
	src/mainboard/roda/rv11/Kconfig.name \
	src/mainboard/razer/blade_stealth_kbl/Kconfig \
	src/mainboard/razer/blade_stealth_kbl/Kconfig.name \
	src/mainboard/raptor-cs/talos-2/Kconfig \
	src/mainboard/raptor-cs/talos-2/Kconfig.name \
	src/mainboard/purism/librem_bdw/Kconfig \
	src/mainboard/purism/librem_cnl/Kconfig \
	src/mainboard/purism/librem_jsl/Kconfig \
	src/mainboard/purism/librem_l1um_v2/Kconfig \
	src/mainboard/purism/librem_skl/Kconfig \
	src/mainboard/purism/librem_bdw/Kconfig.name \
	src/mainboard/purism/librem_cnl/Kconfig.name \
	src/mainboard/purism/librem_jsl/Kconfig.name \
	src/mainboard/purism/librem_l1um_v2/Kconfig.name \
	src/mainboard/purism/librem_skl/Kconfig.name \
	src/mainboard/protectli/vault_adl_n/Kconfig \
	src/mainboard/protectli/vault_adl_p/Kconfig \
	src/mainboard/protectli/vault_bsw/Kconfig \
	src/mainboard/protectli/vault_cml/Kconfig \
	src/mainboard/protectli/vault_ehl/Kconfig \
	src/mainboard/protectli/vault_glk/Kconfig \
	src/mainboard/protectli/vault_jsl/Kconfig \
	src/mainboard/protectli/vault_kbl/Kconfig \
	src/mainboard/protectli/vault_adl_n/Kconfig.name \
	src/mainboard/protectli/vault_adl_p/Kconfig.name \
	src/mainboard/protectli/vault_bsw/Kconfig.name \
	src/mainboard/protectli/vault_cml/Kconfig.name \
	src/mainboard/protectli/vault_ehl/Kconfig.name \
	src/mainboard/protectli/vault_glk/Kconfig.name \
	src/mainboard/protectli/vault_jsl/Kconfig.name \
	src/mainboard/protectli/vault_kbl/Kconfig.name \
	src/mainboard/prodrive/atlas/Kconfig \
	src/mainboard/prodrive/hermes/Kconfig \
	src/mainboard/prodrive/atlas/Kconfig.name \
	src/mainboard/prodrive/hermes/Kconfig.name \
	src/mainboard/portwell/m107/Kconfig \
	src/mainboard/portwell/m107/Kconfig.name \
	src/mainboard/pine64/rockpro64/Kconfig \
	src/mainboard/pine64/rockpro64/Kconfig.name \
	src/mainboard/pcengines/apu2/Kconfig \
	src/mainboard/pcengines/apu2/Kconfig.name \
	src/mainboard/packardbell/ms2290/Kconfig \
	src/mainboard/packardbell/ms2290/Kconfig.name \
	src/mainboard/opencellular/elgon/Kconfig \
	src/mainboard/opencellular/elgon/Kconfig.name \
	src/mainboard/ocp/deltalake/Kconfig \
	src/mainboard/ocp/tiogapass/Kconfig \
	src/mainboard/ocp/deltalake/Kconfig.name \
	src/mainboard/ocp/tiogapass/Kconfig.name \
	src/mainboard/novacustom/adl-p/Kconfig \
	src/mainboard/novacustom/mtl-h/Kconfig \
	src/mainboard/novacustom/nuc_box/Kconfig \
	src/mainboard/novacustom/tgl-u/Kconfig \
	src/mainboard/novacustom/adl-p/Kconfig.name \
	src/mainboard/novacustom/mtl-h/Kconfig.name \
	src/mainboard/novacustom/nuc_box/Kconfig.name \
	src/mainboard/novacustom/tgl-u/Kconfig.name \
	src/mainboard/msi/h81m-p33/Kconfig \
	src/mainboard/msi/ms7707/Kconfig \
	src/mainboard/msi/ms7d25/Kconfig \
	src/mainboard/msi/ms7e06/Kconfig \
	src/mainboard/msi/h81m-p33/Kconfig.name \
	src/mainboard/msi/ms7707/Kconfig.name \
	src/mainboard/msi/ms7d25/Kconfig.name \
	src/mainboard/msi/ms7e06/Kconfig.name \
	src/mainboard/mitaccomputing/whitestone-2/Kconfig \
	src/mainboard/mitaccomputing/whitestone-2/Kconfig.name \
	src/mainboard/libretrend/lt1000/Kconfig \
	src/mainboard/libretrend/lt1000/Kconfig.name \
	src/mainboard/lenovo/haswell/Kconfig \
	src/mainboard/lenovo/l520/Kconfig \
	src/mainboard/lenovo/m900_tiny/Kconfig \
	src/mainboard/lenovo/m920q/Kconfig \
	src/mainboard/lenovo/s230u/Kconfig \
	src/mainboard/lenovo/t400/Kconfig \
	src/mainboard/lenovo/t410/Kconfig \
	src/mainboard/lenovo/t420/Kconfig \
	src/mainboard/lenovo/t420s/Kconfig \
	src/mainboard/lenovo/t430/Kconfig \
	src/mainboard/lenovo/t430s/Kconfig \
	src/mainboard/lenovo/t520/Kconfig \
	src/mainboard/lenovo/t530/Kconfig \
	src/mainboard/lenovo/t60/Kconfig \
	src/mainboard/lenovo/thinkcentre_a58/Kconfig \
	src/mainboard/lenovo/thinkcentre_m710s/Kconfig \
	src/mainboard/lenovo/x131e/Kconfig \
	src/mainboard/lenovo/x1_carbon_gen1/Kconfig \
	src/mainboard/lenovo/x200/Kconfig \
	src/mainboard/lenovo/x201/Kconfig \
	src/mainboard/lenovo/x220/Kconfig \
	src/mainboard/lenovo/x230/Kconfig \
	src/mainboard/lenovo/x60/Kconfig \
	src/mainboard/lenovo/haswell/Kconfig.name \
	src/mainboard/lenovo/l520/Kconfig.name \
	src/mainboard/lenovo/m900_tiny/Kconfig.name \
	src/mainboard/lenovo/m920q/Kconfig.name \
	src/mainboard/lenovo/s230u/Kconfig.name \
	src/mainboard/lenovo/t400/Kconfig.name \
	src/mainboard/lenovo/t410/Kconfig.name \
	src/mainboard/lenovo/t420/Kconfig.name \
	src/mainboard/lenovo/t420s/Kconfig.name \
	src/mainboard/lenovo/t430/Kconfig.name \
	src/mainboard/lenovo/t430s/Kconfig.name \
	src/mainboard/lenovo/t520/Kconfig.name \
	src/mainboard/lenovo/t530/Kconfig.name \
	src/mainboard/lenovo/t60/Kconfig.name \
	src/mainboard/lenovo/thinkcentre_a58/Kconfig.name \
	src/mainboard/lenovo/thinkcentre_m710s/Kconfig.name \
	src/mainboard/lenovo/x131e/Kconfig.name \
	src/mainboard/lenovo/x1_carbon_gen1/Kconfig.name \
	src/mainboard/lenovo/x200/Kconfig.name \
	src/mainboard/lenovo/x201/Kconfig.name \
	src/mainboard/lenovo/x220/Kconfig.name \
	src/mainboard/lenovo/x230/Kconfig.name \
	src/mainboard/lenovo/x60/Kconfig.name \
	src/mainboard/lattepanda/mu/Kconfig \
	src/mainboard/lattepanda/mu/Kconfig.name \
	src/mainboard/kontron/986lcd-m/Kconfig \
	src/mainboard/kontron/bsl6/Kconfig \
	src/mainboard/kontron/ktqm77/Kconfig \
	src/mainboard/kontron/mal10/Kconfig \
	src/mainboard/kontron/986lcd-m/Kconfig.name \
	src/mainboard/kontron/bsl6/Kconfig.name \
	src/mainboard/kontron/ktqm77/Kconfig.name \
	src/mainboard/kontron/mal10/Kconfig.name \
	src/mainboard/inventec/transformers/Kconfig \
	src/mainboard/inventec/transformers/Kconfig.name \
	src/mainboard/intel/adlrvp/Kconfig \
	src/mainboard/intel/apollolake_rvp/Kconfig \
	src/mainboard/intel/archercity_crb/Kconfig \
	src/mainboard/intel/avenuecity_crb/Kconfig \
	src/mainboard/intel/baskingridge/Kconfig \
	src/mainboard/intel/beechnutcity_crb/Kconfig \
	src/mainboard/intel/cedarisland_crb/Kconfig \
	src/mainboard/intel/coffeelake_rvp/Kconfig \
	src/mainboard/intel/d510mo/Kconfig \
	src/mainboard/intel/d945gclf/Kconfig \
	src/mainboard/intel/dcp847ske/Kconfig \
	src/mainboard/intel/dg41wv/Kconfig \
	src/mainboard/intel/dg43gt/Kconfig \
	src/mainboard/intel/dq67sw/Kconfig \
	src/mainboard/intel/elkhartlake_crb/Kconfig \
	src/mainboard/intel/emeraldlake2/Kconfig \
	src/mainboard/intel/frost_creek/Kconfig \
	src/mainboard/intel/glkrvp/Kconfig \
	src/mainboard/intel/harcuvar/Kconfig \
	src/mainboard/intel/jasperlake_rvp/Kconfig \
	src/mainboard/intel/kblrvp/Kconfig \
	src/mainboard/intel/kunimitsu/Kconfig \
	src/mainboard/intel/leafhill/Kconfig \
	src/mainboard/intel/minnow3/Kconfig \
	src/mainboard/intel/minnowmax/Kconfig \
	src/mainboard/intel/mtlrvp/Kconfig \
	src/mainboard/intel/saddlebrook/Kconfig \
	src/mainboard/intel/shadowmountain/Kconfig \
	src/mainboard/intel/strago/Kconfig \
	src/mainboard/intel/tglrvp/Kconfig \
	src/mainboard/intel/wtm2/Kconfig \
	src/mainboard/intel/adlrvp/Kconfig.name \
	src/mainboard/intel/apollolake_rvp/Kconfig.name \
	src/mainboard/intel/archercity_crb/Kconfig.name \
	src/mainboard/intel/avenuecity_crb/Kconfig.name \
	src/mainboard/intel/baskingridge/Kconfig.name \
	src/mainboard/intel/beechnutcity_crb/Kconfig.name \
	src/mainboard/intel/cedarisland_crb/Kconfig.name \
	src/mainboard/intel/coffeelake_rvp/Kconfig.name \
	src/mainboard/intel/d510mo/Kconfig.name \
	src/mainboard/intel/d945gclf/Kconfig.name \
	src/mainboard/intel/dcp847ske/Kconfig.name \
	src/mainboard/intel/dg41wv/Kconfig.name \
	src/mainboard/intel/dg43gt/Kconfig.name \
	src/mainboard/intel/dq67sw/Kconfig.name \
	src/mainboard/intel/elkhartlake_crb/Kconfig.name \
	src/mainboard/intel/emeraldlake2/Kconfig.name \
	src/mainboard/intel/frost_creek/Kconfig.name \
	src/mainboard/intel/glkrvp/Kconfig.name \
	src/mainboard/intel/harcuvar/Kconfig.name \
	src/mainboard/intel/jasperlake_rvp/Kconfig.name \
	src/mainboard/intel/kblrvp/Kconfig.name \
	src/mainboard/intel/kunimitsu/Kconfig.name \
	src/mainboard/intel/leafhill/Kconfig.name \
	src/mainboard/intel/minnow3/Kconfig.name \
	src/mainboard/intel/minnowmax/Kconfig.name \
	src/mainboard/intel/mtlrvp/Kconfig.name \
	src/mainboard/intel/saddlebrook/Kconfig.name \
	src/mainboard/intel/shadowmountain/Kconfig.name \
	src/mainboard/intel/strago/Kconfig.name \
	src/mainboard/intel/tglrvp/Kconfig.name \
	src/mainboard/intel/wtm2/Kconfig.name \
	src/mainboard/ibm/sbp1/Kconfig \
	src/mainboard/ibm/sbp1/Kconfig.name \
	src/mainboard/ibase/mb899/Kconfig \
	src/mainboard/ibase/mb899/Kconfig.name \
	src/mainboard/hp/280_g2/Kconfig \
	src/mainboard/hp/elitebook_820_g2/Kconfig \
	src/mainboard/hp/folio_9480m/Kconfig \
	src/mainboard/hp/pro_3500_series/Kconfig \
	src/mainboard/hp/snb_ivb_desktops/Kconfig \
	src/mainboard/hp/snb_ivb_laptops/Kconfig \
	src/mainboard/hp/280_g2/Kconfig.name \
	src/mainboard/hp/elitebook_820_g2/Kconfig.name \
	src/mainboard/hp/folio_9480m/Kconfig.name \
	src/mainboard/hp/pro_3500_series/Kconfig.name \
	src/mainboard/hp/snb_ivb_desktops/Kconfig.name \
	src/mainboard/hp/snb_ivb_laptops/Kconfig.name \
	src/mainboard/hardkernel/odroid-h4/Kconfig \
	src/mainboard/hardkernel/odroid-h4/Kconfig.name \
	src/mainboard/google/asurada/Kconfig \
	src/mainboard/google/auron/Kconfig \
	src/mainboard/google/beltino/Kconfig \
	src/mainboard/google/brox/Kconfig \
	src/mainboard/google/brya/Kconfig \
	src/mainboard/google/butterfly/Kconfig \
	src/mainboard/google/cherry/Kconfig \
	src/mainboard/google/corsola/Kconfig \
	src/mainboard/google/cyan/Kconfig \
	src/mainboard/google/daisy/Kconfig \
	src/mainboard/google/dedede/Kconfig \
	src/mainboard/google/drallion/Kconfig \
	src/mainboard/google/eve/Kconfig \
	src/mainboard/google/fatcat/Kconfig \
	src/mainboard/google/fizz/Kconfig \
	src/mainboard/google/foster/Kconfig \
	src/mainboard/google/gale/Kconfig \
	src/mainboard/google/geralt/Kconfig \
	src/mainboard/google/glados/Kconfig \
	src/mainboard/google/gru/Kconfig \
	src/mainboard/google/guybrush/Kconfig \
	src/mainboard/google/hatch/Kconfig \
	src/mainboard/google/herobrine/Kconfig \
	src/mainboard/google/jecht/Kconfig \
	src/mainboard/google/kahlee/Kconfig \
	src/mainboard/google/kukui/Kconfig \
	src/mainboard/google/link/Kconfig \
	src/mainboard/google/mistral/Kconfig \
	src/mainboard/google/myst/Kconfig \
	src/mainboard/google/nyan/Kconfig \
	src/mainboard/google/nyan_big/Kconfig \
	src/mainboard/google/nyan_blaze/Kconfig \
	src/mainboard/google/oak/Kconfig \
	src/mainboard/google/octopus/Kconfig \
	src/mainboard/google/parrot/Kconfig \
	src/mainboard/google/peach_pit/Kconfig \
	src/mainboard/google/poppy/Kconfig \
	src/mainboard/google/puff/Kconfig \
	src/mainboard/google/rambi/Kconfig \
	src/mainboard/google/rauru/Kconfig \
	src/mainboard/google/reef/Kconfig \
	src/mainboard/google/rex/Kconfig \
	src/mainboard/google/sarien/Kconfig \
	src/mainboard/google/skyrim/Kconfig \
	src/mainboard/google/skywalker/Kconfig \
	src/mainboard/google/slippy/Kconfig \
	src/mainboard/google/smaug/Kconfig \
	src/mainboard/google/storm/Kconfig \
	src/mainboard/google/stout/Kconfig \
	src/mainboard/google/trogdor/Kconfig \
	src/mainboard/google/veyron/Kconfig \
	src/mainboard/google/veyron_mickey/Kconfig \
	src/mainboard/google/veyron_rialto/Kconfig \
	src/mainboard/google/volteer/Kconfig \
	src/mainboard/google/zork/Kconfig \
	src/mainboard/google/asurada/Kconfig.name \
	src/mainboard/google/auron/Kconfig.name \
	src/mainboard/google/beltino/Kconfig.name \
	src/mainboard/google/brox/Kconfig.name \
	src/mainboard/google/brya/Kconfig.name \
	src/mainboard/google/butterfly/Kconfig.name \
	src/mainboard/google/cherry/Kconfig.name \
	src/mainboard/google/corsola/Kconfig.name \
	src/mainboard/google/cyan/Kconfig.name \
	src/mainboard/google/daisy/Kconfig.name \
	src/mainboard/google/dedede/Kconfig.name \
	src/mainboard/google/drallion/Kconfig.name \
	src/mainboard/google/eve/Kconfig.name \
	src/mainboard/google/fatcat/Kconfig.name \
	src/mainboard/google/fizz/Kconfig.name \
	src/mainboard/google/foster/Kconfig.name \
	src/mainboard/google/gale/Kconfig.name \
	src/mainboard/google/geralt/Kconfig.name \
	src/mainboard/google/glados/Kconfig.name \
	src/mainboard/google/gru/Kconfig.name \
	src/mainboard/google/guybrush/Kconfig.name \
	src/mainboard/google/hatch/Kconfig.name \
	src/mainboard/google/herobrine/Kconfig.name \
	src/mainboard/google/jecht/Kconfig.name \
	src/mainboard/google/kahlee/Kconfig.name \
	src/mainboard/google/kukui/Kconfig.name \
	src/mainboard/google/link/Kconfig.name \
	src/mainboard/google/mistral/Kconfig.name \
	src/mainboard/google/myst/Kconfig.name \
	src/mainboard/google/nyan/Kconfig.name \
	src/mainboard/google/nyan_big/Kconfig.name \
	src/mainboard/google/nyan_blaze/Kconfig.name \
	src/mainboard/google/oak/Kconfig.name \
	src/mainboard/google/octopus/Kconfig.name \
	src/mainboard/google/parrot/Kconfig.name \
	src/mainboard/google/peach_pit/Kconfig.name \
	src/mainboard/google/poppy/Kconfig.name \
	src/mainboard/google/puff/Kconfig.name \
	src/mainboard/google/rambi/Kconfig.name \
	src/mainboard/google/rauru/Kconfig.name \
	src/mainboard/google/reef/Kconfig.name \
	src/mainboard/google/rex/Kconfig.name \
	src/mainboard/google/sarien/Kconfig.name \
	src/mainboard/google/skyrim/Kconfig.name \
	src/mainboard/google/skywalker/Kconfig.name \
	src/mainboard/google/slippy/Kconfig.name \
	src/mainboard/google/smaug/Kconfig.name \
	src/mainboard/google/storm/Kconfig.name \
	src/mainboard/google/stout/Kconfig.name \
	src/mainboard/google/trogdor/Kconfig.name \
	src/mainboard/google/veyron/Kconfig.name \
	src/mainboard/google/veyron_mickey/Kconfig.name \
	src/mainboard/google/veyron_rialto/Kconfig.name \
	src/mainboard/google/volteer/Kconfig.name \
	src/mainboard/google/zork/Kconfig.name \
	src/mainboard/gigabyte/ga-945gcm-s2l/Kconfig \
	src/mainboard/gigabyte/ga-b75m-d3h/Kconfig \
	src/mainboard/gigabyte/ga-d510ud/Kconfig \
	src/mainboard/gigabyte/ga-g41m-es2l/Kconfig \
	src/mainboard/gigabyte/ga-h61m-series/Kconfig \
	src/mainboard/gigabyte/ga-h77m-d3h/Kconfig \
	src/mainboard/gigabyte/ga-945gcm-s2l/Kconfig.name \
	src/mainboard/gigabyte/ga-b75m-d3h/Kconfig.name \
	src/mainboard/gigabyte/ga-d510ud/Kconfig.name \
	src/mainboard/gigabyte/ga-g41m-es2l/Kconfig.name \
	src/mainboard/gigabyte/ga-h61m-series/Kconfig.name \
	src/mainboard/gigabyte/ga-h77m-d3h/Kconfig.name \
	src/mainboard/getac/p470/Kconfig \
	src/mainboard/getac/p470/Kconfig.name \
	src/mainboard/framework/azalea/Kconfig \
	src/mainboard/framework/azalea/Kconfig.name \
	src/mainboard/foxconn/d41s/Kconfig \
	src/mainboard/foxconn/g41s-k/Kconfig \
	src/mainboard/foxconn/d41s/Kconfig.name \
	src/mainboard/foxconn/g41s-k/Kconfig.name \
	src/mainboard/facebook/fbg1701/Kconfig \
	src/mainboard/facebook/monolith/Kconfig \
	src/mainboard/facebook/fbg1701/Kconfig.name \
	src/mainboard/facebook/monolith/Kconfig.name \
	src/mainboard/example/min86/Kconfig \
	src/mainboard/example/min86/Kconfig.name \
	src/mainboard/erying/tgl/Kconfig \
	src/mainboard/erying/tgl/Kconfig.name \
	src/mainboard/emulation/qemu-aarch64/Kconfig \
	src/mainboard/emulation/qemu-armv7/Kconfig \
	src/mainboard/emulation/qemu-i440fx/Kconfig \
	src/mainboard/emulation/qemu-power8/Kconfig \
	src/mainboard/emulation/qemu-power9/Kconfig \
	src/mainboard/emulation/qemu-q35/Kconfig \
	src/mainboard/emulation/qemu-riscv/Kconfig \
	src/mainboard/emulation/qemu-sbsa/Kconfig \
	src/mainboard/emulation/spike-riscv/Kconfig \
	src/mainboard/emulation/qemu-aarch64/Kconfig.name \
	src/mainboard/emulation/qemu-armv7/Kconfig.name \
	src/mainboard/emulation/qemu-i440fx/Kconfig.name \
	src/mainboard/emulation/qemu-power8/Kconfig.name \
	src/mainboard/emulation/qemu-power9/Kconfig.name \
	src/mainboard/emulation/qemu-q35/Kconfig.name \
	src/mainboard/emulation/qemu-riscv/Kconfig.name \
	src/mainboard/emulation/qemu-sbsa/Kconfig.name \
	src/mainboard/emulation/spike-riscv/Kconfig.name \
	src/mainboard/dell/e6400/Kconfig \
	src/mainboard/dell/e7240/Kconfig \
	src/mainboard/dell/optiplex_3050/Kconfig \
	src/mainboard/dell/optiplex_9020/Kconfig \
	src/mainboard/dell/snb_ivb_latitude/Kconfig \
	src/mainboard/dell/snb_ivb_workstations/Kconfig \
	src/mainboard/dell/xps_8300/Kconfig \
	src/mainboard/dell/e6400/Kconfig.name \
	src/mainboard/dell/e7240/Kconfig.name \
	src/mainboard/dell/optiplex_3050/Kconfig.name \
	src/mainboard/dell/optiplex_9020/Kconfig.name \
	src/mainboard/dell/snb_ivb_latitude/Kconfig.name \
	src/mainboard/dell/snb_ivb_workstations/Kconfig.name \
	src/mainboard/dell/xps_8300/Kconfig.name \
	src/mainboard/cwwk/adl/Kconfig \
	src/mainboard/cwwk/adl/Kconfig.name \
	src/mainboard/compulab/intense_pc/Kconfig \
	src/mainboard/compulab/intense_pc/Kconfig.name \
	src/mainboard/clevo/adl-p/Kconfig \
	src/mainboard/clevo/cml-u/Kconfig \
	src/mainboard/clevo/kbl-u/Kconfig \
	src/mainboard/clevo/tgl-u/Kconfig \
	src/mainboard/clevo/adl-p/Kconfig.name \
	src/mainboard/clevo/cml-u/Kconfig.name \
	src/mainboard/clevo/kbl-u/Kconfig.name \
	src/mainboard/clevo/tgl-u/Kconfig.name \
	src/mainboard/cavium/cn8100_sff_evb/Kconfig \
	src/mainboard/cavium/cn8100_sff_evb/Kconfig.name \
	src/mainboard/bytedance/bd_egs/Kconfig \
	src/mainboard/bytedance/bd_egs/Kconfig.name \
	src/mainboard/bostentech/gbyt4/Kconfig \
	src/mainboard/bostentech/gbyt4/Kconfig.name \
	src/mainboard/biostar/th61-itx/Kconfig \
	src/mainboard/biostar/th61-itx/Kconfig.name \
	src/mainboard/asus/h61-series/Kconfig \
	src/mainboard/asus/maximus_iv_gene-z/Kconfig \
	src/mainboard/asus/p2b/Kconfig \
	src/mainboard/asus/p5gc-mx/Kconfig \
	src/mainboard/asus/p5qc/Kconfig \
	src/mainboard/asus/p5ql-em/Kconfig \
	src/mainboard/asus/p5qpl-am/Kconfig \
	src/mainboard/asus/p8x7x-series/Kconfig \
	src/mainboard/asus/h61-series/Kconfig.name \
	src/mainboard/asus/maximus_iv_gene-z/Kconfig.name \
	src/mainboard/asus/p2b/Kconfig.name \
	src/mainboard/asus/p5gc-mx/Kconfig.name \
	src/mainboard/asus/p5qc/Kconfig.name \
	src/mainboard/asus/p5ql-em/Kconfig.name \
	src/mainboard/asus/p5qpl-am/Kconfig.name \
	src/mainboard/asus/p8x7x-series/Kconfig.name \
	src/mainboard/asrock/b75m-itx/Kconfig \
	src/mainboard/asrock/b75pro3-m/Kconfig \
	src/mainboard/asrock/b85m_pro4/Kconfig \
	src/mainboard/asrock/fatal1ty_z87_professional/Kconfig \
	src/mainboard/asrock/g41c-gs/Kconfig \
	src/mainboard/asrock/h110m/Kconfig \
	src/mainboard/asrock/h77pro4-m/Kconfig \
	src/mainboard/asrock/h81m-hds/Kconfig \
	src/mainboard/asrock/imb-1222/Kconfig \
	src/mainboard/asrock/spc741d8/Kconfig \
	src/mainboard/asrock/z87e-itx/Kconfig \
	src/mainboard/asrock/z87m_oc_formula/Kconfig \
	src/mainboard/asrock/z97_extreme6/Kconfig \
	src/mainboard/asrock/z97e-itx_ac/Kconfig \
	src/mainboard/asrock/b75m-itx/Kconfig.name \
	src/mainboard/asrock/b75pro3-m/Kconfig.name \
	src/mainboard/asrock/b85m_pro4/Kconfig.name \
	src/mainboard/asrock/fatal1ty_z87_professional/Kconfig.name \
	src/mainboard/asrock/g41c-gs/Kconfig.name \
	src/mainboard/asrock/h110m/Kconfig.name \
	src/mainboard/asrock/h77pro4-m/Kconfig.name \
	src/mainboard/asrock/h81m-hds/Kconfig.name \
	src/mainboard/asrock/imb-1222/Kconfig.name \
	src/mainboard/asrock/spc741d8/Kconfig.name \
	src/mainboard/asrock/z87e-itx/Kconfig.name \
	src/mainboard/asrock/z87m_oc_formula/Kconfig.name \
	src/mainboard/asrock/z97_extreme6/Kconfig.name \
	src/mainboard/asrock/z97e-itx_ac/Kconfig.name \
	src/mainboard/arm/rdn2/Kconfig \
	src/mainboard/arm/rdn2/Kconfig.name \
	src/mainboard/apple/macbook21/Kconfig \
	src/mainboard/apple/macbookair4_2/Kconfig \
	src/mainboard/apple/macbook21/Kconfig.name \
	src/mainboard/apple/macbookair4_2/Kconfig.name \
	src/mainboard/aopen/dxplplusu/Kconfig \
	src/mainboard/aopen/dxplplusu/Kconfig.name \
	src/mainboard/aoostar/wtr_r1/Kconfig \
	src/mainboard/aoostar/wtr_r1/Kconfig.name \
	src/mainboard/amd/bilby/Kconfig \
	src/mainboard/amd/birman/Kconfig \
	src/mainboard/amd/birman_plus/Kconfig \
	src/mainboard/amd/chausie/Kconfig \
	src/mainboard/amd/gardenia/Kconfig \
	src/mainboard/amd/majolica/Kconfig \
	src/mainboard/amd/mandolin/Kconfig \
	src/mainboard/amd/mayan/Kconfig \
	src/mainboard/amd/onyx_poc/Kconfig \
	src/mainboard/amd/pademelon/Kconfig \
	src/mainboard/amd/bilby/Kconfig.name \
	src/mainboard/amd/birman/Kconfig.name \
	src/mainboard/amd/birman_plus/Kconfig.name \
	src/mainboard/amd/chausie/Kconfig.name \
	src/mainboard/amd/gardenia/Kconfig.name \
	src/mainboard/amd/majolica/Kconfig.name \
	src/mainboard/amd/mandolin/Kconfig.name \
	src/mainboard/amd/mayan/Kconfig.name \
	src/mainboard/amd/onyx_poc/Kconfig.name \
	src/mainboard/amd/pademelon/Kconfig.name \
	src/mainboard/acer/aspire_vn7_572g/Kconfig \
	src/mainboard/acer/g43t-am3/Kconfig \
	src/mainboard/acer/aspire_vn7_572g/Kconfig.name \
	src/mainboard/acer/g43t-am3/Kconfig.name \
	src/mainboard/51nb/x210/Kconfig \
	src/mainboard/51nb/x210/Kconfig.name \
	src/mainboard/51nb/Kconfig \
	src/mainboard/acer/Kconfig \
	src/mainboard/amd/Kconfig \
	src/mainboard/aoostar/Kconfig \
	src/mainboard/aopen/Kconfig \
	src/mainboard/apple/Kconfig \
	src/mainboard/arm/Kconfig \
	src/mainboard/asrock/Kconfig \
	src/mainboard/asus/Kconfig \
	src/mainboard/biostar/Kconfig \
	src/mainboard/bostentech/Kconfig \
	src/mainboard/bytedance/Kconfig \
	src/mainboard/cavium/Kconfig \
	src/mainboard/clevo/Kconfig \
	src/mainboard/compulab/Kconfig \
	src/mainboard/cwwk/Kconfig \
	src/mainboard/dell/Kconfig \
	src/mainboard/emulation/Kconfig \
	src/mainboard/erying/Kconfig \
	src/mainboard/example/Kconfig \
	src/mainboard/facebook/Kconfig \
	src/mainboard/foxconn/Kconfig \
	src/mainboard/framework/Kconfig \
	src/mainboard/getac/Kconfig \
	src/mainboard/gigabyte/Kconfig \
	src/mainboard/google/Kconfig \
	src/mainboard/hardkernel/Kconfig \
	src/mainboard/hp/Kconfig \
	src/mainboard/ibase/Kconfig \
	src/mainboard/ibm/Kconfig \
	src/mainboard/intel/Kconfig \
	src/mainboard/inventec/Kconfig \
	src/mainboard/kontron/Kconfig \
	src/mainboard/lattepanda/Kconfig \
	src/mainboard/lenovo/Kconfig \
	src/mainboard/libretrend/Kconfig \
	src/mainboard/mitaccomputing/Kconfig \
	src/mainboard/msi/Kconfig \
	src/mainboard/novacustom/Kconfig \
	src/mainboard/ocp/Kconfig \
	src/mainboard/opencellular/Kconfig \
	src/mainboard/packardbell/Kconfig \
	src/mainboard/pcengines/Kconfig \
	src/mainboard/pine64/Kconfig \
	src/mainboard/portwell/Kconfig \
	src/mainboard/prodrive/Kconfig \
	src/mainboard/protectli/Kconfig \
	src/mainboard/purism/Kconfig \
	src/mainboard/raptor-cs/Kconfig \
	src/mainboard/razer/Kconfig \
	src/mainboard/roda/Kconfig \
	src/mainboard/samsung/Kconfig \
	src/mainboard/sapphire/Kconfig \
	src/mainboard/siemens/Kconfig \
	src/mainboard/sifive/Kconfig \
	src/mainboard/starlabs/Kconfig \
	src/mainboard/supermicro/Kconfig \
	src/mainboard/system76/Kconfig \
	src/mainboard/ti/Kconfig \
	src/mainboard/topton/Kconfig \
	src/mainboard/up/Kconfig \
	src/mainboard/via/Kconfig \
	src/mainboard/51nb/Kconfig.name \
	src/mainboard/acer/Kconfig.name \
	src/mainboard/amd/Kconfig.name \
	src/mainboard/aoostar/Kconfig.name \
	src/mainboard/aopen/Kconfig.name \
	src/mainboard/apple/Kconfig.name \
	src/mainboard/arm/Kconfig.name \
	src/mainboard/asrock/Kconfig.name \
	src/mainboard/asus/Kconfig.name \
	src/mainboard/biostar/Kconfig.name \
	src/mainboard/bostentech/Kconfig.name \
	src/mainboard/bytedance/Kconfig.name \
	src/mainboard/cavium/Kconfig.name \
	src/mainboard/clevo/Kconfig.name \
	src/mainboard/compulab/Kconfig.name \
	src/mainboard/cwwk/Kconfig.name \
	src/mainboard/dell/Kconfig.name \
	src/mainboard/emulation/Kconfig.name \
	src/mainboard/erying/Kconfig.name \
	src/mainboard/example/Kconfig.name \
	src/mainboard/facebook/Kconfig.name \
	src/mainboard/foxconn/Kconfig.name \
	src/mainboard/framework/Kconfig.name \
	src/mainboard/getac/Kconfig.name \
	src/mainboard/gigabyte/Kconfig.name \
	src/mainboard/google/Kconfig.name \
	src/mainboard/hardkernel/Kconfig.name \
	src/mainboard/hp/Kconfig.name \
	src/mainboard/ibase/Kconfig.name \
	src/mainboard/ibm/Kconfig.name \
	src/mainboard/intel/Kconfig.name \
	src/mainboard/inventec/Kconfig.name \
	src/mainboard/kontron/Kconfig.name \
	src/mainboard/lattepanda/Kconfig.name \
	src/mainboard/lenovo/Kconfig.name \
	src/mainboard/libretrend/Kconfig.name \
	src/mainboard/mitaccomputing/Kconfig.name \
	src/mainboard/msi/Kconfig.name \
	src/mainboard/novacustom/Kconfig.name \
	src/mainboard/ocp/Kconfig.name \
	src/mainboard/opencellular/Kconfig.name \
	src/mainboard/packardbell/Kconfig.name \
	src/mainboard/pcengines/Kconfig.name \
	src/mainboard/pine64/Kconfig.name \
	src/mainboard/portwell/Kconfig.name \
	src/mainboard/prodrive/Kconfig.name \
	src/mainboard/protectli/Kconfig.name \
	src/mainboard/purism/Kconfig.name \
	src/mainboard/raptor-cs/Kconfig.name \
	src/mainboard/razer/Kconfig.name \
	src/mainboard/roda/Kconfig.name \
	src/mainboard/samsung/Kconfig.name \
	src/mainboard/sapphire/Kconfig.name \
	src/mainboard/siemens/Kconfig.name \
	src/mainboard/sifive/Kconfig.name \
	src/mainboard/starlabs/Kconfig.name \
	src/mainboard/supermicro/Kconfig.name \
	src/mainboard/system76/Kconfig.name \
	src/mainboard/ti/Kconfig.name \
	src/mainboard/topton/Kconfig.name \
	src/mainboard/up/Kconfig.name \
	src/mainboard/via/Kconfig.name \
	src/mainboard/Kconfig \
	src/sbom/Kconfig \
	src/Kconfig \

include/config/auto.conf: $(deps_config)


$(deps_config): ;
